# Travis-CI config
language: cpp
compiler: gcc

addons:
  apt:
    packages:
    - gdb

before_install: yes yes | sudo cpan -fi Unix::Processors Parallel::Forker Bit::Vector
before_script: nproc; autoconf
script: ./configure && make -j 2 && make test && cd test_regress && ./driver.pl --j 0
