# Travis-CI config
language: cpp
compiler: gcc

# Some tests require gdb
addons:
  apt:
    packages:
    - gdb

env:
  - TEST=t_a_first_cc
  - TEST=t_flag_csplit

# Perl modules needed for testing
before_install: yes yes | sudo cpan -fi Unix::Processors Parallel::Forker Bit::Vector
before_script: nproc; autoconf
#script: ./configure && make -j 2 && make test && cd test_regress && ./driver.pl --j 0
script: ./configure && make -j 2 && make test && test_regress/t/$TEST.pl --verbose
after_script: make -C test_regress/obj_vlt/$TEST/ -f V$TEST.mk debug-make
